name: 'seedwing-action'
description: 'Enforce seedwing policies on your project'
author: 'seedwing-io team'
branding:
  icon: play-circle
  color: gray-dark
inputs:
  root:
    description: Path to the root of the project, containing the .enforcer.yaml file. Defaults to the workspace.
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.root }}
