name: 'seedwing-action'
description: 'Enforce seedwing policies on your project'
author: 'seedwing-io team'
branding:
  icon: play-circle
  color: gray-dark
inputs:
  enforcer-config:
    description: Path to configuration file for the enforcer.
    required: true # TODO: should become optional, default to root
  source: # should be dropped and come from the enforcer config
    description: Path to the manifest file. pom.xml and Cargo.toml file are auto-detected. Defaults to the project root.
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.enforcer-config }}
    - ${{ inputs.source }}
